import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";
import type { AdapterPluginToolDescriptor } from "@paperclipai/adapter-utils";

// JSON-stringify a value as a JS expression literal (safe + valid JS for the
// object literals we emit into the generated extension file).
const js = (v: unknown) => JSON.stringify(v ?? {});

/**
 * Sanitize a plugin tool name for LLM-facing tool registration. OpenAI-compatible
 * providers require `^[a-zA-Z0-9_-]+$` — namespaced names like
 * `paperclip.company-defaults:create_pr` are rejected with a 400. The ORIGINAL
 * name is still used when dispatching to the execute endpoint.
 */
export function sanitizeToolName(name: string): string {
  return name.replace(/[^a-zA-Z0-9_-]/g, "_");
}

/**
 * Render a pi extension that registers one LLM-callable tool per plugin tool
 * descriptor. Each tool's `execute()` POSTs to the Paperclip plugin-tool
 * execute endpoint, authenticated with the agent's `PAPERCLIP_API_KEY`, and
 * carries `runContext` built from the agent's env.
 *
 * The generated source is plain JS (ESM), not TS, because the pi binary loads
 * extension files at runtime.
 */
export function renderPluginToolExtension(descriptors: AdapterPluginToolDescriptor[]): string {
  const registrations = descriptors
    .map(
      (d) => `  pi.registerTool({
    name: ${js(sanitizeToolName(d.name))},
    label: ${js(d.displayName)},
    description: ${js(d.description)},
    // typebox is JSON Schema, so the descriptor's parametersSchema is passed through directly.
    parameters: ${js(d.parametersSchema)},
    async execute(_toolCallId, params) {
      return exec(${js(d.name)}, params);
    },
  });`,
    )
    .join("\n");

  return `// AUTO-GENERATED by the pi_local adapter — exposes Paperclip plugin tools to the agent.
const API = process.env.PAPERCLIP_API_URL;
const KEY = process.env.PAPERCLIP_API_KEY;
const RUN = {
  agentId: process.env.PAPERCLIP_AGENT_ID,
  runId: process.env.PAPERCLIP_RUN_ID,
  companyId: process.env.PAPERCLIP_COMPANY_ID,
  projectId: process.env.PAPERCLIP_PROJECT_ID,
};
async function exec(tool, parameters) {
  const resp = await fetch(API + "/api/plugins/tools/execute", {
    method: "POST",
    headers: { "Content-Type": "application/json", Authorization: "Bearer " + KEY },
    body: JSON.stringify({ tool, parameters: parameters ?? {}, runContext: RUN }),
  });
  const data = await resp.json().catch(() => ({ error: "non-json response" }));
  const text = typeof data === "string" ? data : JSON.stringify(data);
  return { content: [{ type: "text", text: resp.ok ? text : "Error: " + text }], details: data };
}

export default function (pi) {
${registrations}
}
`;
}

/** Write the extension to `<dir>/plugin-tools.mjs` and return its path. */
export async function writePluginToolExtension(
  descriptors: AdapterPluginToolDescriptor[],
  dir: string,
): Promise<string> {
  await mkdir(dir, { recursive: true });
  const path = join(dir, "plugin-tools.mjs");
  await writeFile(path, renderPluginToolExtension(descriptors), "utf8");
  return path;
}
